### ISSUE TITLE
Load Error on run

### ISSUE THREAD

**Issue by semaperepelitsa** [kaievns/pentix.rb#1]
I get the following error when I try to launch `pentix.rb`

```
~/code/pentix.rb[master]% ruby pentix.rb 
/Users/sema/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- /Users/sema/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.28-universal-darwin/lib/gosu.bundle (LoadError)
    from /Users/sema/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.28-universal-darwin/lib/gosu.rb:12:in `rescue in <top (required)>'
    from /Users/sema/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.28-universal-darwin/lib/gosu.rb:3:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in `rescue in require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from pentix.rb:9:in `<main>'
```

**Comment by kaievns** [comment]
gosu недавно обновились криво, откатитесь на `0.7.27.1` и все заработает

**Comment by kaievns** [comment]
поговорил с автором, он обновил гем, теперь все работает

**Comment by semaperepelitsa** [comment]
Благодарю :-) Кстати, я у вас вижу Gemfile, но в самой программе Bundler не используется. Можно включить следующие строки в `pentix.rb`, чтобы таких проблем больше не было:

```
require 'rubygems'
require 'bundler/setup'
```

**Comment by kaievns** [comment]
можно и включить, спасибо за наводку :)
